language: python
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make test_xunit

after_success:
  - make docker_push

deploy:
  provider: heroku
  app: floating-coast-87004
  api_key: ${HEROKU_API_KEY}
